### ISSUE TITLE
Premature exit issues on Windows

### ISSUE THREAD

**Issue by mikealeonetti** [mologie/curl-asio#6]
I'm using your code on Windows with libcurl compiled static using mingw32. It was compiled with zlib and openssl.

I'm using the following code:

```
		// Our response holder
		boost::shared_ptr<std::stringstream> string_stream( new std::stringstream );
			// TODO
			const std::string json_string( "{ \"test\" : true }" );

			// Get a CURL style
			const std::shared_ptr<curl::easy> curl( new curl::easy( curl_multi_ ) );

			curl->add_header( "Content-Type: application/json" );
			curl->add_header( "Accept: application/json" );
			curl->set_post( 1 );
			curl->set_ssl_verify_host( 0 );
			curl->set_ssl_verify_peer( 0 );
			curl->set_post_fields( json_string );
			curl->set_sink( string_stream );
			curl->set_timeout( 60 );
			curl->set_url( "https://survivor:8181/help" );
			curl->set_debug_data( this );
			curl->set_debug_callback( &Notify::debugCallbackStatic );
			curl->set_verbose( true );

			// No
			curl->async_perform( [ this, curl, string_stream ]( const boost::system::error_code &error ) { } );
```

To check out the error. It doesn't matter what URL I use, when it's HTTPS it'll hang with an error. For some reason it fails right after the handshake. curl_mutli_ is attached to a running boost::asio::io_service. I can see the timers firing calling socket_action(CURL_SOCKET_TIMEOUT, 0); but then all of the sudden it receives a CURL_POLL_REMOVE. Then it just waits the 59 seconds and times out.

This is where it fails in the debug:

> 2017-02-16, 16:16:32.178800: <trace> (0x000008dc) [Notify] TLSv1.2 (OUT), TLS change cipher, Client hello (1):
> 
> 2017-02-16, 16:16:32.178800: <trace> (0x000008dc) [Notify] => Send SSL data (1 bytes): 
> 2017-02-16, 16:16:32.178800: <trace> (0x000008dc) [Notify] => Send SSL data (5 bytes):  <
> 2017-02-16, 16:16:32.178800: <trace> (0x000008dc) [Notify] TLSv1.2 (OUT), TLS handshake, Unknown (67):
> 
> 2017-02-16, 16:16:32.178800: <trace> (0x000008dc) [Notify] => Send SSL data (36 bytes): C   http/1.1                      
> 2017-02-16, 16:16:32.178800: <trace> (0x000008dc) [Notify] => Send SSL data (5 bytes):  (
> 2017-02-16, 16:16:32.178800: <trace> (0x000008dc) [Notify] TLSv1.2 (OUT), TLS handshake, Finished (20):
> 
> 2017-02-16, 16:16:32.178800: <trace> (0x000008dc) [Notify] => Send SSL data (16 bytes):   AªÅ:gJZ0(?„
> 2017-02-16, 16:17:31.302800: <trace> (0x000008dc) [Notify] Curl_http_done: called premature == 1

If I use CURL by itself blocking it works just fine. I'm wondering what the issue is and if you've encountered it.

**Comment by mologie** [comment]
Hi, I haven't been using this project myself for roughly 3 years now. It may happen that I dig it out again for a future project of mine, but think that a good chunk of code will have to be updated for C++11/14 and standalone Asio.

If you must use curl with the Asio event loop and find it worth to resolve the issues you experience with this project, then I'll gladly work with you to integrate your changes. I however do not have the resources to investigate your issue right now. I'll leave it open for visibility.

**Comment by mikealeonetti** [comment]
Thanks mologie for the response. It actually seemed to be an issue with libcurl's release version 7.52.1 and windows+mingw. Using it with the snapshot February 17, 2017 makes it work just fine. I'm closing this bug as it works with the code now.
