### ISSUE TITLE
Would this library work with io_context running on multiple threads?

### ISSUE THREAD

**Issue by mikealeonetti** [mologie/curl-asio#8]
I was just wondering if I were to do this in a worker thread scenario, if I called io_context.run() on multiple threads, and fed that io context to the multi class, would it work or would it probably crash?

Basically, is it thread safe to do that?

**Comment by mologie** [comment]
This library is a thin wrapper around libcurl's API, which is not thread safe.

You'll need to use strands (io_context::strand) or a comparable technique to synchronize access.

Please beware though: This library is currently unmaintained by me, so you might be on your own at debugging errors.
